# Generated by Django 4.1.4 on 2022-12-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_alter_formrequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='formrequest',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
