# Generated by Django 4.1.4 on 2022-12-17 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_form_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='slug',
        ),
    ]
