# Generated by Django 4.1.4 on 2022-12-20 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0011_form_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formrequest',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_request', to='forms.form'),
        ),
    ]
