# Generated by Django 4.1.4 on 2022-12-18 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0012_formrequest_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formrequest',
            name='ip',
        ),
    ]
