# Generated by Django 4.1.4 on 2022-12-20 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0013_alter_formrequest_form_alter_formrequest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formrequest',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_requests', to='forms.form'),
        ),
        migrations.CreateModel(
            name='SubmitSuccessMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('message', models.TextField(max_length=700)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submit_success', to=settings.AUTH_USER_MODEL)),
                ('form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='forms.form')),
            ],
        ),
    ]
