# Generated by Django 4.1.4 on 2022-12-21 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0015_alter_submitsuccessmessage_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitsuccessmessage',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submit_success_form', to='forms.form'),
        ),
    ]
