# Generated by Django 4.1.4 on 2022-12-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0016_alter_submitsuccessmessage_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='formrequest',
            name='view',
            field=models.BooleanField(default=False),
        ),
    ]
