# Generated by Django 4.1.4 on 2022-12-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0018_alter_submitsuccessmessage_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitsuccessmessage',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
