# Generated by Django 4.1.4 on 2022-12-27 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0019_submitsuccessmessage_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubmitSuccessMessage',
        ),
    ]
