# Generated by Django 4.1.4 on 2023-01-02 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0022_formrequest_as_anonim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='submit_success',
        ),
    ]
