# Generated by Django 4.1.4 on 2023-01-06 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0023_remove_form_submit_success'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='profile/profile.jpg', upload_to='profile')),
                ('bio', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('is_online', models.BooleanField(default=False)),
                ('is_verify', models.BooleanField(default=False)),
                ('custom_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'My Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
    ]
