# Generated by Django 4.1.4 on 2023-01-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0024_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile/profile_14TGeRN.png', upload_to='profile'),
        ),
    ]
