# Generated by Django 4.1.4 on 2023-01-18 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0028_profile_github_profile_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gplus',
        ),
    ]
