# Generated by Django 4.1.4 on 2023-01-18 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0029_remove_profile_gplus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='telegram',
        ),
    ]
