# Generated by Django 4.1.4 on 2023-01-21 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0031_dashboardform_customuser_view_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardform',
            name='form',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_form', to='forms.form'),
        ),
    ]
