# Generated by Django 4.1.4 on 2023-01-21 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0032_alter_dashboardform_form'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboardform',
            old_name='view_on',
            new_name='last_visit',
        ),
        migrations.RenameField(
            model_name='dashboardform',
            old_name='views',
            new_name='visits',
        ),
    ]
