# Generated by Django 4.1.4 on 2023-01-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0033_rename_view_on_dashboardform_last_visit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardform',
            name='visits',
            field=models.IntegerField(default=0),
        ),
    ]
