# Generated by Django 4.1.4 on 2023-01-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0037_formrequest_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formrequest',
            name='description',
            field=models.TextField(max_length=70),
        ),
    ]
