# Generated by Django 4.1.4 on 2023-01-28 16:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0038_alter_formrequest_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='formrequest',
            name='submited_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
