# Generated by Django 4.1.4 on 2023-02-13 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0040_form_message_en_form_message_uz_form_title_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='message_uz',
            new_name='message_ru',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='title_uz',
            new_name='title_ru',
        ),
    ]
