# Generated by Django 4.1.4 on 2023-02-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0041_rename_message_uz_form_message_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='message_uz',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='title_uz',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
