# Generated by Django 4.1.4 on 2023-03-04 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0048_formvisits'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormVisits',
        ),
    ]
