# Generated by Django 4.1.4 on 2023-03-24 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0050_remove_formrequest_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='view_form',
        ),
    ]
