# Generated by Django 4.1.4 on 2023-05-22 15:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0052_dashboardform_users_cant_send'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardform',
            name='users_cant_send',
        ),
        migrations.RemoveField(
            model_name='dashboardform',
            name='uwsr',
        ),
        migrations.AddField(
            model_name='dashboardform',
            name='sent_the_request',
            field=models.ManyToManyField(related_name='sent_the_request', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dashboardform',
            name='users_that_cannot_send_requests',
            field=models.ManyToManyField(related_name='users_that_cannot_send_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
